In [1]:
import numpy as np
import pandas as pd

##Question 1 :  Write a Python program to check whether a number is even or odd using conditional statements.

In [3]:
num=int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))

Enter a number: 2
2 is Even


##Question 2 : Write a Python program to count how many times a number appears in a list.

Example List

[2,3,4,2,5,2]

In [5]:
numbers=[2,3,4,2,5,2]
num=int(input("Enter number to count: "))
count=numbers.count(num)
print("count:", count)

Enter number to count: 2
count: 3


###Question 3 :  Generate an array from 1 to 20 with step size 2.

In [6]:
arr=np.arange(1,21,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


###Question 4 : Create a new column called Revenue, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.

In [17]:
import pandas as pd
data = {'Quantity': [10, 5, 8, 12],
        'Price': [2.5, 10.0, 4.0, 1.5],
        'Region': ['South', 'North', 'East', 'South']}
df = pd.DataFrame(data)

df['Revenue'] = df['Quantity'] * df['Price']
print(df)

   Quantity  Price Region  Revenue
0        10    2.5  South     25.0
1         5   10.0  North     50.0
2         8    4.0   East     32.0
3        12    1.5  South     18.0


###Question 5 : Convert a 1D array into 2x3 matrix:

arr = np.array([1,2,3,4,5,6])

In [9]:
arr=np.array([1,2,3,4,5,6])
matrix=arr.reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


###Question 6 : Slicing Data

1)Select first 10 rows

2)Select only "Product Category" and "Quantity" columns

1) Select first 10 rows

In [10]:
print(df.iloc[:10])



   Quantity  Price  Revenue
0        10    2.5     25.0
1         5   10.0     50.0
2         8    4.0     32.0
3        12    1.5     18.0


2) Select only "Product Category" and "Quantity" columns

In [12]:
print("first 10 rows:")
print(df.iloc[:10,])
print("\nQuantity column:")
print(df[["Quantity"]])

first 10 rows:
   Quantity  Price  Revenue
0        10    2.5     25.0
1         5   10.0     50.0
2         8    4.0     32.0
3        12    1.5     18.0

Quantity column:
   Quantity
0        10
1         5
2         8
3        12


###Question 7 : Find all records where:

Region = "South" and Quantity > 2

In [18]:
result=df[(df["Region"]=="South")&
          (df["Quantity"]>2)]
print(result)

   Quantity  Price Region  Revenue
0        10    2.5  South     25.0
3        12    1.5  South     18.0


###Question 8 : Display:

1) The first 10 rows of the dataset.

2) Rows 15 to 25.

1) The first 10 rows of the dataset.

In [19]:
print(df.iloc[:10])

   Quantity  Price Region  Revenue
0        10    2.5  South     25.0
1         5   10.0  North     50.0
2         8    4.0   East     32.0
3        12    1.5  South     18.0


2) Rows 15 to 25.

In [21]:
print("frist 10 rows:")
print(df.iloc[:10])
print("\nRows 15 to 25:")
print(df.iloc[14:25])

frist 10 rows:
   Quantity  Price Region  Revenue
0        10    2.5  South     25.0
1         5   10.0  North     50.0
2         8    4.0   East     32.0
3        12    1.5  South     18.0

Rows 15 to 25:
Empty DataFrame
Columns: [Quantity, Price, Region, Revenue]
Index: []


###Question 9 : Create a random array of 10 numbers and:

. Find max and min

. Sort the array


In [22]:
arr=np.random.randint(1,100,10)
print("Original Array",arr)
print("Maximum Value:",np.max(arr))
print("Minimum Value:",np.min(arr))
print("Sorted Array:",np.sort(arr))

Original Array [45 52 15 10 97 60 54 95 51 66]
Maximum Value: 97
Minimum Value: 10
Sorted Array: [10 15 45 51 52 54 60 66 95 97]


###Question 10 : Replace all even numbers with 0:

arr = np.array([1,2,3,4,5,6])

In [28]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr[arr % 2 == 0] = 0
print(arr)

[1 0 3 0 5 0]
